# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: ["main"]
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.swift"
      - "**.yml"
  workflow_dispatch:

jobs:
  masOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v --enable-code-coverage
      - name: Convert coverage files
        run: |
          xcrun llvm-cov export -format "lcov" \
          .build/debug/ChartDPackageTests.xctest/Contents/MacOS/ChartDPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          file: info.lcov
